FROM debian:bookworm-slim

RUN apt-get update && \
    apt-get install -y \
      libssl-dev \
      tini \
      ca-certificates && \
      rm -rf /tmp/* /var/{tmp,cache}/* /var/lib/{apt,dpkg}/

COPY ./target/release/shielder-relayer /usr/local/bin
RUN chmod +x /usr/local/bin/shielder-relayer

RUN useradd server
USER server

ENTRYPOINT ["tini", "--", "shielder-relayer"]
