[package]
name = "shielder-contract"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
categories.workspace = true
repository.workspace = true

[dependencies]
thiserror = "2.0.10"
rand = "0.9.0-beta.1"
