---
name: "Prepare Contracts environment"
description: >
  Installs Foundry toolchain, installs contracts npm dependencies

runs:
  using: composite
  steps:
    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1.3.1
      with:
        cache-key: custom-seed-coverage-${{ github.ref_name }}
        cache-restore-keys: |-
          contract-suite
        version: v1.0.0

    - name: Contract deps
      run: make deps
