---
name: "Prepare Rust environment"
description: Installs Rust toolchain

runs:
  using: composite
  steps:
    - name: Install Rust toolchain
      uses: Cardinal-Cryptography/github-actions/install-rust-toolchain@v7
      with:
        channel: nightly

    - name: Install active toolchain
      shell: bash
      run: rustup toolchain install

    - name: Install sccache
      shell: bash
      run: scripts/install-sccache
