---
name: Build and push docker image

inputs:
  aws-mainnet-ecr-access-key:
    required: true
  aws-mainnet-ecr-access-key-id:
    required: true
  ecr-private-host:
    description: ECR private host
    required: true

outputs:
  image_tag:
    description: Tag of the pushed image
    value: ${{ steps.outputs.outputs.image_tag }}

runs:
  using: composite
  steps:
    - name: Call action get-ref-properties
      id: get-ref-properties
      uses: Cardinal-Cryptography/github-actions/get-ref-properties@v6

    - name: DOCKER | Login to private Amazon ECR
      id: login-private-ecr
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.ecr-private-host }}
        username: ${{ inputs.aws-mainnet-ecr-access-key-id }}
        password: ${{ inputs.aws-mainnet-ecr-access-key }}
      env:
        AWS_REGION: us-east-1

    - name: DOCKER | Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: v0.9.1

    - name: DOCKER | Build and push latest docker image
      id: build-image
      uses: docker/build-push-action@v3
      with:
        context: .
        builder: ${{ steps.buildx.outputs.name }}
        file: ./crates/shielder-relayer/docker/Dockerfile.client
        push: true
        tags: "${{ inputs.ecr-private-host }}/shielder-relayer:\
          ${{ steps.get-ref-properties.outputs.sha }}"

    - name: OUTPUTS | Set output with docker image
      id: outputs
      shell: bash
      run: |
        echo "image_tag=${{ steps.get-ref-properties.outputs.sha }}" >> $GITHUB_OUTPUT
