---
name: Deploy docker image

inputs:
  image-tag:
    description: Tag of the docker image to be deployed
    required: true
  autocommit-author:
    description: Commit author
    required: true
  autocommit-email:
    description: Commit author's mail
    required: true
  github-token:
    description: Github token
    required: true
  ecr-private-host:
    description: ECR private host
    required: true
  kustomize-version:
    description: Kustomize version
    required: true
  environment:
    description: Environment to deploy to
    type: choice
    options:
      - all (dev, stage, prod)
      - dev
      - stage
      - prod
    required: true

runs:
  using: composite
  steps:
    - name: GIT | Checkout aleph-apps repo
      uses: actions/checkout@v4
      with:
        repository: Cardinal-Cryptography/aleph-apps
        token: ${{ inputs.github-token }}
        path: "aleph-apps"
        ref: main

    - name: Setup yq
      uses: dcarbone/install-yq-action@v1.3.1
      with:
        version: "v4.44.3"

    - name: Update docker image tag (dev)
      if: ${{ inputs.environment == 'dev' || inputs.environment == 'all (dev, stage, prod)' }}
      shell: bash
      run: |
        cd aleph-apps/shielder-relayer-v2
        yq -iy '.relayer.image.tag = "${{ inputs.image-tag }}"' dev-values.yaml

    - name: Update docker image tag (stage)
      if: ${{ inputs.environment == 'stage' || inputs.environment == 'all (dev, stage, prod)' }}
      shell: bash
      run: |
        cd aleph-apps/shielder-relayer-v2
        yq -iy '.relayer.image.tag = "${{ inputs.image-tag }}"' stage-values.yaml

    - name: Update docker image tag (prod)
      if: ${{ inputs.environment == 'prod' || inputs.environment == 'all (dev, stage, prod)' }}
      shell: bash
      run: |
        cd aleph-apps/shielder-relayer-v2
        yq -iy '.relayer.image.tag = "${{ inputs.image-tag }}"' prod-values.yaml

    - name: GIT | Commit changes to aleph-apps repository
      uses: EndBug/add-and-commit@v9.1.4
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        author_name: ${{ inputs.autocommit-author }}
        author_email: ${{ inputs.autocommit-email }}
        message: >
          Updating shielder-relayer on environment: ${{ inputs.environment }}
          docker image tag: ${{ inputs.image-tag }}
        add: "*.yaml"
        cwd: 'aleph-apps'
