---
name: Deploy docker image

inputs:
  image-tag:
    description: Tag of the docker image to be deployed
    required: true
  autocommit-author:
    description: Commit author
    required: true
  autocommit-email:
    description: Commit author's mail
    required: true
  github-token:
    description: Github token
    required: true
  environment:
    description: Environment to deploy to
    type: choice
    options:
      - all
      - stage
    required: true

runs:
  using: composite
  steps:
    - name: GIT | Checkout aleph-apps repo
      uses: actions/checkout@v4
      with:
        repository: Cardinal-Cryptography/blanksquare-apps
        token: ${{ inputs.github-token }}
        path: "blanksquare-apps"
        ref: main

    - name: Setup yq
      uses: dcarbone/install-yq-action@v1.3.1
      with:
        version: "v4.44.3"

    - name: Update docker image tag (stage)
      if: ${{ inputs.environment == 'stage' || inputs.environment == 'all' }}
      shell: bash
      run: |
        cd blanksquare-apps/shielder-v3/stage
        yq -i '.shielder-relayer.relayer.image.tag = "${{ inputs.image-tag }}"' values.yaml

    - name: GIT | Commit changes to aleph-apps repository
      uses: EndBug/add-and-commit@v9.1.4
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        author_name: ${{ inputs.autocommit-author }}
        author_email: ${{ inputs.autocommit-email }}
        message: >
          Updating shielder-relayer on environment: ${{ inputs.environment }}
          docker image tag: ${{ inputs.image-tag }}
        add: "*.yaml"
        cwd: 'blanksquare-apps'
