---
name: Build wasm packages

on:
  workflow_call:
  workflow_dispatch:

jobs:
  main:
    name: Build wasm packages
    runs-on: [self-hosted, Linux, X64, large]
    timeout-minutes: 10

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Prepare Rust env
        uses: ./.github/actions/prepare-rust-env

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build shielder_bindings
        run: cd crates/shielder_bindings && make wasm && make wasm-without-circuits

      - name: Upload generated wasm to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wasm-pkg
          path: crates/shielder_bindings/pkg
          retention-days: 1

      - name: Upload generated wasm without circuits to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wasm-pkg-without-circuits
          path: crates/shielder_bindings/pkg-without-circuits
          retention-days: 1

      - name: Upload generated proving keys to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: proving-keys-pkg
          path: crates/shielder_bindings/artifacts
          retention-days: 1
