---
#  This workflow checks if vars and secrets are present and fails if one is empty.
#  It should be included as a first step in all the workflows.
name: Check vars and secrets
on:
  workflow_call:

jobs:
  main:
    name: Check available vars and secrets
    runs-on: ubuntu-22.04
    steps:
      - name: Check vars
        run: |
          if [[ \
            -z '${{ vars.CI_TESTNET_ALICE_PUBLIC_KEY }}' || \
            -z '${{ vars.CI_TESTNET_BOB_PUBLIC_KEY }}' || \
            -z '${{ vars.CI_TESTNET_CHARLIE_PUBLIC_KEY }}' || \
            -z '${{ vars.CI_TESTNET_FEE_DESTINATION }}' || \
            -z '${{ vars.CI_TESTNET_RELAYER_SIGNER_ADDRESSES }}' || \
            -z '${{ vars.CI_TESTNET_STAGE_OWNER_ADDRESS }}' || \
            -z '${{ vars.CI_TESTNET_TS_SDK_PUBLIC_KEY }}' || \
            -z '${{ vars.ECR_PUBLIC_HOST }}' || \
            -z '${{ vars.ECR_CC_RES_PUBLIC_REGISTRY }}'
          ]]; then
            echo '!!! Some repository variables are either missing or empty.'
            echo '!!! Please check either repository or organization settings.'
            exit 1
          fi

      - name: Check secrets
        run: |
          if [[ \
            -z '${{ secrets.AWS_MAINNET_ECR_CC_ACCESS_KEY }}' || \
            -z '${{ secrets.AWS_MAINNET_ECR_CC_ACCESS_KEY_ID }}' || \
            -z '${{ secrets.CI_GH_TOKEN }}' || \
            -z '${{ secrets.CI_TESTNET_ALICE_PRIVATE_KEY }}' || \
            -z '${{ secrets.CI_TESTNET_BOB_PRIVATE_KEY }}' || \
            -z '${{ secrets.CI_TESTNET_CHARLIE_PRIVATE_KEY }}' || \
            -z '${{ secrets.CI_TESTNET_DEPLOYER_PRIVATE_KEY }}' || \
            -z '${{ secrets.CI_TESTNET_FEE_DESTINATION_KEY }}' || \
            -z '${{ secrets.CI_TESTNET_RELAYER_SIGNING_KEYS }}' || \
            -z '${{ secrets.CI_TESTNET_TS_SDK_PRIVATE_KEY }}' || \
            -z '${{ secrets.NPM_PUBLISHING_KEY }}' || \
            -z '${{ secrets.SLACK_WEBHOOK_ZKOS }}' || \

            -z '${{ secrets.AUTOCOMMIT_AUTHOR }}' || \
            -z '${{ secrets.AUTOCOMMIT_EMAIL }}' || \
            -z '${{ secrets.DOCKERHUB_USERNAME }}' || \
            -z '${{ secrets.DOCKERHUB_PASSWORD }}'
          ]]; then
            echo '!!! Some repository secrets are either missing or empty.'
            echo '!!! Please check either repository or organization settings.'
            exit 1
          fi
