---
#  This workflow checks if vars and secrets are present and fails if one is empty.
#  It should be included as a first step in all the workflows.
name: Check vars and secrets
on:
  workflow_call:

jobs:
  main:
    name: Check available vars and secrets
    runs-on: ubuntu-22.04
    steps:
      - name: Check vars
        run: |
          if [[ \
            -z '${{ vars.KUSTOMIZE_VERSION }}' || \
            -z '${{ vars.CI_TESTNET_ALICE_PUBLIC_KEY }}' || \
            -z '${{ vars.CI_TESTNET_BOB_PUBLIC_KEY }}' || \
            -z '${{ vars.CI_TESTNET_CHARLIE_PUBLIC_KEY }}' || \
            -z '${{ vars.CI_TESTNET_FEE_DESTINATION }}' || \
            -z '${{ vars.CI_TESTNET_RELAYER_SIGNER_ADDRESSES }}' || \
            -z '${{ vars.CI_TESTNET_STAGE_OWNER_ADDRESS }}' || \
            -z '${{ vars.CI_TESTNET_TS_SDK_PUBLIC_KEY }}' || \
            -z '${{ vars.MAINNET_PROD_OWNER_ADDRESS }}' || \
            -z '${{ vars.SHIELDER_CONTRACT_ADDRESS }}'
          ]]; then
            echo '!!! Some repository variables are either missing or empty.'
            echo '!!! Please check either repository or organization settings.'
            exit 1
          fi

      - name: Check secrets
        run: |
          if [[ \
            -z '${{ secrets.AWS_MAINNET_ECR_ACCESS_KEY }}' || \
            -z '${{ secrets.AWS_MAINNET_ECR_ACCESS_KEY_ID }}' || \
            -z '${{ secrets.CI_GH_TOKEN }}' || \
            -z '${{ secrets.CI_MAINNET_DEPLOYER_PRIVATE_KEY }}' || \
            -z '${{ secrets.CI_TESTNET_ALICE_PRIVATE_KEY }}' || \
            -z '${{ secrets.CI_TESTNET_BOB_PRIVATE_KEY }}' || \
            -z '${{ secrets.CI_TESTNET_CHARLIE_PRIVATE_KEY }}' || \
            -z '${{ secrets.CI_TESTNET_DEPLOYER_PRIVATE_KEY }}' || \
            -z '${{ secrets.CI_TESTNET_FEE_DESTINATION_KEY }}' || \
            -z '${{ secrets.CI_TESTNET_RELAYER_SIGNING_KEYS }}' || \
            -z '${{ secrets.CI_TESTNET_TS_SDK_PRIVATE_KEY }}' || \
            -z '${{ secrets.NPM_PUBLISHING_KEY }}' || \
            -z '${{ secrets.SLACK_WEBHOOK_ZKOS }}' || \
            -z '${{ secrets.VERCEL_ORG_ID }}' || \
            -z '${{ secrets.VERCEL_PROJECT_ID }}' || \
            -z '${{ secrets.VERCEL_TOKEN }}' || \
            -z '${{ secrets.ZKOS_CIRCUITS_SSH_PRIVATE_KEY }}' || \

            -z '${{ secrets.AUTOCOMMIT_AUTHOR }}' || \
            -z '${{ secrets.AUTOCOMMIT_EMAIL }}' || \
            -z '${{ secrets.CONTRACTS_S3BUCKET_NAME }}' || \
            -z '${{ secrets.CONTRACTS_S3BUCKET_REGION }}' || \
            -z '${{ secrets.CONTRACTS_ZKOS_ADDRESSES_MAINNET_PROD_RW_AWS_ACCESS_KEY_ID }}' || \
            -z '${{ secrets.CONTRACTS_ZKOS_ADDRESSES_MAINNET_PROD_RW_AWS_SECRET_ACCESS_KEY }}' || \
            -z '${{ secrets.CONTRACTS_ZKOS_ADDRESSES_TESTNET_DEV_RW_AWS_ACCESS_KEY_ID }}' || \
            -z '${{ secrets.CONTRACTS_ZKOS_ADDRESSES_TESTNET_DEV_RW_AWS_SECRET_ACCESS_KEY }}' || \
            -z '${{ secrets.CONTRACTS_ZKOS_ADDRESSES_TESTNET_STAGE_RW_AWS_ACCESS_KEY_ID }}' || \
            -z '${{ secrets.CONTRACTS_ZKOS_ADDRESSES_TESTNET_STAGE_RW_AWS_SECRET_ACCESS_KEY }}' || \
            -z '${{ secrets.CONTRACTS_ZKOS_ARTIFACTS_RW_AWS_ACCESS_KEY_ID }}' || \
            -z '${{ secrets.CONTRACTS_ZKOS_ARTIFACTS_RW_AWS_SECRET_ACCESS_KEY }}' || \
            -z '${{ secrets.ECR_PRIVATE_HOST }}' || \
            -z '${{ secrets.SSH_PRIVATE_KEY }}' || \
            -z '${{ secrets.DOCKERHUB_USERNAME }}' || \
            -z '${{ secrets.DOCKERHUB_PASSWORD }}'
          ]]; then
            echo '!!! Some repository secrets are either missing or empty.'
            echo '!!! Please check either repository or organization settings.'
            exit 1
          fi
