---
name: Deploy contracts

on:
  workflow_call:
  workflow_dispatch:

jobs:
  main:
    name: Deploy contracts to the anvil network
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: asdf-vm/actions/install@v3

      - name: Prepare Solidity environment
        uses: ./.github/actions/prepare-sol-env

      - name: Run anvil node in background
        shell: bash
        run: make anvil &

      - name: Download generated contracts from artifacts
        uses: actions/download-artifact@v4
        with:
          name: generated-contracts
          path: contracts

      - name: Download compiled contracts from artifacts
        uses: actions/download-artifact@v4
        with:
          name: contract-artifacts
          path: artifacts

      - name: Download generated build cache
        uses: actions/download-artifact@v4
        with:
          name: generated-build-cache
          path: cache

      - name: deploy eth contracts
        shell: bash
        run: NETWORK=anvil make deploy-contracts
