---
name: Measure circuits

on:
  workflow_dispatch:
  workflow_call:

jobs:
  main:
    name: Measure circuits
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:

      - name: Prepare Rust env
        uses: ./.github/actions/prepare-rust-env
        with:
          poseidon-gadget-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          zkos-circuits-private-key: ${{ secrets.ZKOS_CIRCUITS_SSH_PRIVATE_KEY }}

      #################### Run measurements on the current branch ####################

      - name: Checkout code (from the current branch)
        uses: actions/checkout@v4

      - name: Run measure-circuits binary on the current branch
        run: |
             cd crates/integration-tests
             cargo run --bin gas-consumption -- ../../current-report.txt

      #################### Run measurements on the main branch ####################

      - name: Checkout repository from `main`
        uses: actions/checkout@v4
        with:
          ref: main
          path: main

      - name: Run measure-circuits on the `main` branch
        run: |
          cd main/crates/integration-tests
          cargo run --bin gas-consumption -- ../../../main-report.txt

      #################### Generate report ####################

      - name: Install Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run metrics-diff-presenter script
        run: python3 .github/scripts/gas_diff.py

      - name: Post measurements difference
        if: ${{ hashFiles('report.html') != '' }}
        uses: thollander/actions-comment-pull-request@v3
        with:
          file-path: report.html
          comment-tag: gas-measurements-diff

