---
name: Measure gas

on:
  workflow_dispatch:
  workflow_call:

jobs:
  main:
    name: Measure gas and verifier code size
    runs-on: [self-hosted, Linux, X64, large]
    timeout-minutes: 20
    steps:
      - name: Checkout code (from the current branch)
        uses: actions/checkout@v4

      - name: Prepare Rust env
        uses: ./.github/actions/prepare-rust-env
        with:
          poseidon-gadget-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          zkos-circuits-private-key: ${{ secrets.ZKOS_CIRCUITS_SSH_PRIVATE_KEY }}

      - name: Setup node
        uses: asdf-vm/actions/install@v3

      - name: Install solc compiler
        uses: ./.github/actions/install-solc
        with:
          solc-version: 0.8.26

      #################### Run measurements on the current branch ####################

      - name: Build binary
        run: cargo build -p integration-tests --bin gas-consumption --release

      - name: Install dependencies
        run: make deps

      - name: Generate all contracts
        run: make generate-contracts

      - name: Compile all contracts
        run: make compile-contracts

      - name: Run gas-consumption binary on the current branch
        run: |
          export CONTRACTS_DIR="contracts"
          export CARGO_MANIFEST_DIR=./Cargo.toml
          ./target/release/gas-consumption current-gas.txt

      - name: Print gas measured on the current branch
        run: cat current-gas.txt

      - name: Measure verifiers code size
        run: |
          echo -n "Deposit: " > current-size.txt
          cat ./artifacts/DepositVerifier.sol/Halo2Verifier.json \
            | jq -r '.bytecode.object' | wc -c >> current-size.txt
          echo -n "Withdraw: " >> current-size.txt
          cat ./artifacts/WithdrawVerifier.sol/Halo2Verifier.json \
            | jq -r '.bytecode.object' | wc -c >> current-size.txt
          echo -n "NewAccount: " >> current-size.txt
          cat ./artifacts/NewAccountVerifier.sol/Halo2Verifier.json \
            | jq -r '.bytecode.object' | wc -c >> current-size.txt

      #################### Run measurements on the main branch ####################

      - name: Checkout repository from `main`
        uses: actions/checkout@v4
        with:
          ref: main
          path: main

      - name: Build binary
        run: |
          cd main
          cargo build -p integration-tests --bin gas-consumption --release

      - name: Install dependencies
        working-directory: main
        run: make deps

      - name: Generate all contracts
        working-directory: main
        run: make generate-contracts

      - name: Compile all contracts
        working-directory: main
        run: make compile-contracts

      - name: Build binary (main branch)
        working-directory: main
        run: cargo build -p integration-tests --bin gas-consumption --release

      - name: Run gas-consumption on the `main` branch
        run: |
          export CONTRACTS_DIR="main/contracts"
          export CARGO_MANIFEST_DIR=./main/Cargo.toml
          ./main/target/release/gas-consumption main-gas.txt

      - name: Print gas measured on the `main` branch
        run: cat main-gas.txt

      - name: Measure verifiers code size
        run: |
          echo -n "Deposit: " > main-size.txt
          cat ./main/artifacts/DepositVerifier.sol/Halo2Verifier.json \
            | jq -r '.bytecode.object' | wc -c >> main-size.txt
          echo -n "Withdraw: " >> main-size.txt
          cat ./main/artifacts/WithdrawVerifier.sol/Halo2Verifier.json \
            | jq -r '.bytecode.object' | wc -c >> main-size.txt
          echo -n "NewAccount: " >> main-size.txt
          cat ./main/artifacts/NewAccountVerifier.sol/Halo2Verifier.json \
            | jq -r '.bytecode.object' | wc -c >> main-size.txt

      #################### Generate report ####################

      - name: Install Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install python deps
        run: pip install prettytable

      - name: Run metrics-diff-presenter script
        run: python3 .github/scripts/gas_size_diff.py > report.html

      - name: Print gas and size report with diff
        run: cat report.html

      - name: Post measurements difference
        uses: thollander/actions-comment-pull-request@v3
        with:
          file-path: report.html
          comment-tag: hashFiles('report.html')
