---

name: "Build enclaves"
on:
  pull_request:
jobs:
  build-and-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "tee/nix"
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Call action get-ref-properties
        id: get-ref-properties
        uses: Cardinal-Cryptography/github-actions/get-ref-properties@v7

      - name: Install nix
        uses: cachix/install-nix-action@v31

      - name: Check nix inputs
        run: nix flake check

      - name: Build enclave for shielder-prover-tee
        run: |
          nix build --override-input \ 
            zkOS-monorepo 'github:Cardinal-Cryptography/zkOS-monorepo/${{ steps.get-ref-properties.outputs.full-sha }}'
