---
name: "Build and deploy shielder-relayer"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy to
        type: choice
        options:
          - all
          - dev
          - stage
          - prod
        required: true
      branch:
        description: "Branch to check out (by default: main)"
        type: string
        default: main
        required: true

jobs:
  build-and-push:
    name: Build and push shielder-relayer
    runs-on: [self-hosted, Linux, X64, medium]
    steps:
      - name: GIT | Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Prepare Rust env
        uses: ./.github/actions/prepare-rust-env

      - name: Build relayer
        run: cd crates/shielder-relayer && make build

      - name: DOCKER | Build and push
        uses: ./.github/actions/shielder-relayer/build-and-push
        id: build_shielder_relayer
        with:
          aws-mainnet-ecr-access-key-id: ${{ secrets.AWS_MAINNET_ECR_ACCESS_KEY_ID }}
          aws-mainnet-ecr-access-key: ${{ secrets.AWS_MAINNET_ECR_ACCESS_KEY }}
          ecr-private-host: ${{ secrets.ECR_PRIVATE_HOST }}
    outputs:
      image_tag: ${{ steps.build_shielder_relayer.outputs.image_tag }}

  deploy:
    name: Deploy shielder-relayer
    needs: [build-and-push]
    runs-on: [self-hosted, Linux, X64, medium]
    steps:
      - name: GIT | Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Deploy
        uses: ./.github/actions/shielder-relayer/deploy
        id: deploy_shielder_relayer
        with:
          environment: prod
          image-tag: ${{ needs.build-and-push.outputs.image_tag }}
          autocommit-author: ${{ secrets.AUTOCOMMIT_AUTHOR }}
          autocommit-email: ${{ secrets.AUTOCOMMIT_EMAIL }}
          github-token: ${{ secrets.CI_GH_TOKEN }}
          kustomize-version: ${{ vars.KUSTOMIZE_VERSION }}
          ecr-private-host: ${{ secrets.ECR_PRIVATE_HOST }}
