---

name: "Build enclaves"
on:
  pull_request:
  push:
    branches:
      - "main"
jobs:
  build-and-check:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: "tee/nix"
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - run: nix build
      - run: nix flake check
