---
name: "[TESTNET] Deploy contracts"

on:
  workflow_dispatch:

jobs:
  deploy-contracts:
    name: Deploy contracts on testnet
    runs-on: [self-hosted, Linux, X64, medium]
    steps:
      - name: GIT | Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Prepare Rust env
        uses: ./.github/actions/prepare-rust-env
        with:
          poseidon-gadget-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          zkos-circuits-private-key: ${{ secrets.ZKOS_CIRCUITS_SSH_PRIVATE_KEY }}

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1.2.0
        with:
          cache-key: custom-seed-coverage-${{ github.ref_name }}
          cache-restore-keys: |-
            contract-suite
          version: nightly-31dd1f77fd9156d09836486d97963cec7f555343

      - name: Install deps
        run: make deps

      - name: Compile eth contracts
        run: make compile-contracts

      - name: Deploy contracts
        run: PRIVATE_KEY= ${{ secrets.CI_TESTNET_DEPLOYER_PRIVATE_KEY }} NETWORK=https://rpc.alephzero-testnet.gelato.digital make deploy-contracts

      - name: Verify Shielder contract
        run: make verify-shielder-contract

      - name: Upload Shielder abi to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: shielder_abi
          path: artifacts/Shielder.sol/Shielder.json
          include-hidden-files: true
          retention-days: 14

      - name: Create file with Shielder contract address
        run: echo $(cat broadcast/Shielder.s.sol/2039/run-latest.json | \
          jq -c '.transactions | .[] | select(.contractName=="Shielder") | .contractAddress') \
          > shielder_address.txt

      - name: Upload Shielder contract address to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: shielder_address
          path: shielder_address.txt
          include-hidden-files: true
          retention-days: 14
